// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriberInterface is a mock of SubscriberInterface interface.
type MockSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberInterfaceMockRecorder
}

// MockSubscriberInterfaceMockRecorder is the mock recorder for MockSubscriberInterface.
type MockSubscriberInterfaceMockRecorder struct {
	mock *MockSubscriberInterface
}

// NewMockSubscriberInterface creates a new mock instance.
func NewMockSubscriberInterface(ctrl *gomock.Controller) *MockSubscriberInterface {
	mock := &MockSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriberInterface) EXPECT() *MockSubscriberInterfaceMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockSubscriberInterface) Exists(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSubscriberInterfaceMockRecorder) Exists(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSubscriberInterface)(nil).Exists), email)
}
