name: lint

on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  golangci-lint-main:
    name: golangci-lint for main project
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: go work init and download
        run: |
          echo 'go 1.22' > go.work
          echo 'use .' >> go.work
          echo 'use ./mailer' >> go.work
          go mod tidy
          go mod download

      - name: run golangci-lint
        run: golangci-lint run ./...

  golangci-lint-mailer:
    name: golangci-lint for mailer
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: go mod tidy and download for mailer
        run: |
          cd mailer
          go mod tidy
          go mod download

      - name: run golangci-lint for mailer
        run: |
          cd mailer
          golangci-lint run ./...
